name: Build and Push Docker Image

on:
  push:
    branches: [ main ]   # ÙŠØ´ØªØºÙ„ Ù„Ù…Ø§ ØªØ¹Ù…Ù„ push Ø¹Ù„Ù‰ Ø§Ù„ÙØ±Ø¹ Ø§Ù„Ø±Ø¦ÙŠØ³ÙŠ

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ§© Ø³Ø­Ø¨ Ø§Ù„ÙƒÙˆØ¯ Ù…Ù† GitHub
        uses: actions/checkout@v4

      - name: ğŸ”§ ØªØ³Ø¬ÙŠÙ„ Ø§Ù„Ø¯Ø®ÙˆÙ„ ÙÙŠ Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: ğŸ—ï¸ Ø¨Ù†Ø§Ø¡ Ø§Ù„Ù€ Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/myweb:latest .

      - name: ğŸš€ Ø±ÙØ¹ Ø§Ù„Ù€ Image Ø¥Ù„Ù‰ Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/myweb:latest
